# SPDX-FileCopyrightText: 2024 Max Reznik <reznikmm@gmail.com>
#
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name = "ping"
description = "Ping example for TAP driver"
version = "0.1.0-dev"

authors = ["Max Reznik"]
maintainers = ["Max Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["reznikmm"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

[[depends-on]]
enet_tap = "~0.1.0-dev"
"enet" = "*"

[build-profiles]
"enet_tap" = "development"
"enet" = "development"


[[pins]]
enet_tap = { path='../..' }
